version: "3"
services:
    mysql:
        image: mysql:8.4
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: wpr
            MYSQL_PASSWORD: fit2024
            MYSQL_DATABASE: wpr2201040036
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    backend:
        build: .
        depends_on:
            - mysql
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        command:
            [
                "sh",
                "-c",
                "./wait-for-it.sh mysql:3306 -- node dbsetup.js && node index.js",
            ]

volumes:
    mysql_data:
